name: Deno CI
on:
  - push
jobs:
  add_npm:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout action
        uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.38.4"
      - run: deno lint